# Generated by Django 5.1.1 on 2024-09-24 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da categoria', max_length=100, unique=True, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_restaurante', models.CharField(help_text='Nome do produto', max_length=100, unique=True, verbose_name='Nome')),
                ('nome_proprietario', models.CharField(help_text='Nome do produto', max_length=100, unique=True, verbose_name='Nome')),
                ('numero_Proprietario', models.CharField(help_text='Número do endereço', max_length=10, verbose_name='Número')),
                ('numero_contato', models.CharField(help_text='Número do endereço', max_length=10, verbose_name='Número')),
                ('rua', models.CharField(help_text='Rua do endereço', max_length=100, verbose_name='Rua')),
                ('numero', models.CharField(help_text='Número do endereço', max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, help_text='Bairro do endereço', max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(help_text='Cidade do endereço', max_length=100, verbose_name='Cidade')),
                ('cep', models.CharField(help_text='CEP do endereço', max_length=8, verbose_name='CEP')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, help_text='Imagem do produto', null=True, upload_to='produtos', verbose_name='Imagem')),
                ('name', models.CharField(help_text='Nome do produto', max_length=100, unique=True, verbose_name='Nome')),
                ('dsc', models.TextField(blank=True, help_text='Descrição do produto', null=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, help_text='Preço do produto', max_digits=10, verbose_name='Preço')),
                ('ID_Categoria', models.ForeignKey(help_text='Id da categoria do produto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardapio.categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(help_text='Rua do endereço', max_length=100, verbose_name='Rua')),
                ('numero', models.CharField(help_text='Número do endereço', max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, help_text='Complemento do endereço', max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, help_text='Bairro do endereço', max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(help_text='Cidade do endereço', max_length=100, verbose_name='Cidade')),
                ('cep', models.CharField(help_text='CEP do endereço', max_length=8, verbose_name='CEP')),
                ('ID_produto', models.ForeignKey(help_text='Id do Produto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardapio.produto', verbose_name='Produto')),
                ('ID_restaurante', models.ForeignKey(help_text='ID do Restaurante', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardapio.restaurante', verbose_name='Restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='nome do usuario', max_length=100)),
                ('senha', models.CharField(help_text='senha do usuario', max_length=100)),
                ('email', models.EmailField(help_text='email do usuario', max_length=100)),
                ('cpf', models.CharField(help_text='cpf do usuario', max_length=14)),
                ('restaurante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cardapio.restaurante')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
